env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[02ac8cec21dd46193eb5846410dcff77c1081c63e80268460c02c6abfa6a78f66861547377189793805c0e18859a9f71]"
    bot_api: "ENCRYPTED[c162f42e974fcc4c0e3db7607edb9ddc63c973fc37ac3482bc54e42eb780007beff211e16c5f0e2617ffbc19772d8957]"
    tg_id: "ENCRYPTED[f713aa93aa7c710901b7d2330b59268349bcb8b4bd2c364ed9245f102017505e6fff9fe962462a4a1a31b0a5dd5b6b47]"

task:
    name: derpness
    timeout_in: 120m
    container:
      image: inok2341/builder:latest
      cpu: 8
      memory: 32G      

    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    download_ccache_background_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - df -h && free -h && nproc && cat /etc/os* && env
      - curl https://ap.apd1.workers.dev/4:/vayuccache/ccache.tar.gz -o /tmp/ccache.tar.gz
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
      - mkdir -p /tmp/rom
      - cd /tmp/rom
    sync_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Sync ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - git config --global  user.name "rahul9999xda"
      - git config --global  user.email "rahul9999xda@gmail.com"
      - mkdir -p /tmp/rom # Where to sync source
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u git://github.com/DerpFest-11/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault
      - git clone https://github.com/pocox3pro/Local-Manifests -b master --depth=1 .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
    monitor_background_script:
      - ./monitor
    building_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Build ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - ./build
      - time rclone copy /tmp/rom/out/error.log remote:vayuccache -P
    compress_ccache_script:    
      - ./upload

